spring:
  application:
    name: crud-springbboot

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=tienda;encrypt=false
    username: sa
    password: 123

#  jpa:
#    hibernate:
#      ddl-auto: validate
#    show-sql: true

server:
    port: 8081